# Generated by Django 5.1.5 on 2025-03-02 19:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm_chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="is_user",
        ),
        migrations.AddField(
            model_name="message",
            name="meta_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="message",
            name="role",
            field=models.CharField(
                choices=[("A", "Assistant"), ("S", "System"), ("U", "User")],
                default="A",
                max_length=1,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="conversation",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
