# Generated by Django 5.1.5 on 2025-03-14 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("llm_chat", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="role",
            new_name="sender",
        ),
    ]
