# Generated by Django 5.1.4 on 2025-01-23 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title or name of the document", max_length=255
                    ),
                ),
                (
                    "upload_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date when the document was uploaded",
                    ),
                ),
                ("file_path", models.TextField()),
                (
                    "file_checksum",
                    models.CharField(
                        help_text="Unique hash of the file content",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("parsed", "Parsed"),
                            ("pending", "Pending"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Status of document parsing",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Metadata key (e.g., 'Author')", max_length=255
                    ),
                ),
                ("value", models.TextField(help_text="Metadata value")),
                (
                    "document",
                    models.OneToOneField(
                        help_text="The document to which this metadata belongs",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="document_parser.documentstore",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParsedElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "element_id",
                    models.CharField(
                        default="e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
                        max_length=33,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The textual content of the parsed element, if applicable"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Additional metadata associated with the element (e.g., table structure, image data)",
                        null=True,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        help_text="The document from which this element was parsed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parsed_elements",
                        to="document_parser.documentstore",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parsed Element",
                "verbose_name_plural": "Parsed Elements",
            },
        ),
    ]
